apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: three-tier
spec:
  type: ClusterIP
  selector:
    role: frontend
  ports:
    - port: 80          # 👈 REQUIRED for Ingress
      targetPort: 3000  # 👈 containerPort

